### ISSUE TITLE
Import XML not working

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [Meshiest/mlogblocks#1]
I can copy the XML data, but when I press ctrl-v, nothing happens, and the "import xml" button is unclickable. Am I doing something wrong?

**Comment by Meshiest** [comment]
if you import xml, it adds a space to your clipboard to stop you from accidentally importing xml again while you are editing

you can remove the space by pasting and re-copying the xml

**Comment by MoonstreamJustNotInSpace** [comment]
Thanks!

**Comment by MoonstreamJustNotInSpace** [comment]
It doesn't work for me. I pressed ctrl-shift-s and then ctrl-v right afterwards, and it won't work.
![Screen Shot 2021-05-02 at 6 16 52 PM](https://user-images.githubusercontent.com/63458530/116829600-92a76f00-ab72-11eb-86d6-58e59e647237.png)
![Screen Shot 2021-05-02 at 6 17 07 PM](https://user-images.githubusercontent.com/63458530/116829612-9c30d700-ab72-11eb-903b-54598fdee5f3.png)

Also, the button isn't highlighted when I mouse over it, which is weird.

**Comment by Meshiest** [comment]
the ctrl+v is not a button, javascript can't steal clipboard contents without the user explicitly using the paste command

**Comment by MoonstreamJustNotInSpace** [comment]
Okay, that makes sense. Turns out it's cmd-V on Mac. Thanks!
