### ISSUE TITLE
Code gives error, but no explination given.

### ISSUE THREAD

**Issue by LargePrime** [Meshiest/mlogblocks#2]
following code gives error

```
 <xml xmlns="https://developers.google.com/blockly/xml"><variables><variable id="AcE15`,^(od4$!%;LT8/">howlong</variable><variable id="#RFo+f)fM5bg{3Tl6^u~">itemtype</variable></variables><block type="procedures_callnoreturn" id="[WGxZp}FY1{gx%FG/={I" x="870" y="-387"><mutation name="setunloaders"><arg name="itemtype"></arg></mutation><value name="ARG0"><block type="procedures_callreturn" id="eZ-|JN0AlbZK5.S$S-7_"><mutation name="smelterneeds"></mutation></block></value><next><block type="procedures_callnoreturn" id="|}Ppf1~ti+6+OI8CD,CQ"><mutation name="waitabit"><arg name="howlong"></arg></mutation><value name="ARG0"><block type="var_block_text" id="MUIZ0+(@K.(91{fM`l)T"><field name="VALUE">1000</field></block></value><next><block type="mind_end" id="`~wcOxZ_M{.VWl(w,3zM"></block></next></block></next></block><block type="procedures_defnoreturn" id="~_j!OTygYhs49#xXs_lY" x="866" y="-234"><mutation><arg name="howlong" varid="AcE15`,^(od4$!%;LT8/"></arg></mutation><field name="NAME">waitabit</field><comment pinned="false" h="80" w="160">Describe this function...</comment><statement name="STACK"><block type="mind_op_set_binary" id="z-6PNlmWkDMixhCPvSkD"><field name="DEST">result</field><field name="OPERATOR">add</field><value name="A"><shadow type="var_block_text" id="#-eEIFY3-}07r0Ipd+O:"><field name="VALUE">a</field></shadow><block type="global_self" id="]PuzuKV{dbv/wFhMELh("><field name="NAME">@time</field></block></value><value name="B"><shadow type="var_block_text" id="t?[WW~0V*%^scz?,bt},"><field name="VALUE">howlong</field></shadow></value><next><block type="loop_repeat_while" id="{65$-R!SCA.8XK_v6#4%"><value name="COND"><shadow type="var_block_text" id="GhBoBc2wN)CGp[MH5|Cw"><field name="VALUE">true</field></shadow><block type="mind_op_var_binary" id="6}eY/;vT5r.e~2iRPKBF"><field name="OPERATOR">greaterThan</field><value name="A"><shadow type="var_block_text" id="-D_-a?Jb*J!9]ZdOH~+-"><field name="VALUE">result</field></shadow></value><value name="B"><shadow type="var_block_text" id="[#ZaG(s5zvxQ59|1$n3f"><field name="VALUE">b</field></shadow><block type="global_self" id="dA_YIzHE*jFV,9f!%Zq%"><field name="NAME">@time</field></block></value></block></value></block></next></block></statement></block><block type="procedures_defnoreturn" id="uNAxK@r4,gP,Nv(Z{#l3" x="865" y="-69"><mutation><arg name="itemtype" varid="#RFo+f)fM5bg{3Tl6^u~"></arg></mutation><field name="NAME">setunloaders</field><comment pinned="false" h="80" w="160">Sets unloaders to item type</comment><statement name="STACK"><block type="mind_set" id="PTxwxAS1:u+=%wisdig@"><field name="DEST">unloader1</field><value name="VALUE"><shadow type="var_block_text" id="_3K@Q7vAdmgzim@n6)@p"><field name="VALUE">itemtype</field></shadow></value><next><block type="mind_set" id="^Qe7`B)gzX:yZE;uA,T("><field name="DEST">unloader2</field><value name="VALUE"><shadow type="var_block_text" id="yc0x}iA]ifK]=e1vDnS["><field name="VALUE">itemtype</field></shadow></value><next><block type="mind_set" id="f46}LiqUR$)]eiN[q1av"><field name="DEST">unloader3</field><value name="VALUE"><shadow type="var_block_text" id="+)U~!riE.G#Xd;qdt10I"><field name="VALUE">itemtype</field></shadow></value><next><block type="mind_set" id=".?sY[?w23*)17prBLL9{"><field name="DEST">unloader4</field><value name="VALUE"><shadow type="var_block_text" id="$zB4!Ld.LChZ$(UlFPP:"><field name="VALUE">itemtype</field></shadow></value></block></next></block></next></block></next></block></statement></block><block type="procedures_defreturn" id="~Ym*VfYPKQbELGe1Iot." x="862" y="103"><field name="NAME">smelterneeds</field><comment pinned="false" h="80" w="160">Describe this function...</comment><statement name="STACK"><block type="mind_sensor" id="g_5YWfP)XJy*,0Oq3$bI"><field name="DEST">copper</field><value name="FIELD"><shadow type="global_item" id="U(~}9ay00%eGFq_VDyu!"><field name="NAME">@copper</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="Id(9Um}Gg7;Mx,SbE(G9"><field name="VALUE">smelter1</field></shadow></value><next><block type="mind_sensor" id="4O*!_|V*^8=rz%yL*g/+"><field name="DEST">lead</field><value name="FIELD"><shadow type="global_item" id="W*^C2_(h76Ru,??2`*`L"><field name="NAME">@lead</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="1,5Llim08hnMk+`iCm$Y"><field name="VALUE">smelter1</field></shadow></value><next><block type="mind_sensor" id="-~H,FwE+6(O=.`YI_GmO"><field name="DEST">silicon</field><value name="FIELD"><shadow type="global_item" id="wQ:}c{hCHr}3%?w#onQ["><field name="NAME">@silicon</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="v4V^v))_Fdm2h;H9D93l"><field name="VALUE">smelter1</field></shadow></value><next><block type="mind_sensor" id="?FS+LH3JwO1!VSnvhV{G"><field name="DEST">titanium</field><value name="FIELD"><shadow type="global_item" id="=?{}62y|eF2M2g{AdGN`"><field name="NAME">@titanium</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="7OgBLa][:38_V(@*E)tj"><field name="VALUE">smelter1</field></shadow></value><next><block type="mind_set" id="cu{c#7A/DTkeEmW#Meod"><field name="DEST">result</field><value name="VALUE"><shadow type="var_block_text" id="}b)QnSH)ZxUoy(S@OW!["><field name="VALUE">0</field></shadow><block type="logic_ternary" id="rmVkBxkhU8pa?q1CMPm("><value name="IF"><block type="mind_op_var_binary" id="JDYCHeIj-HbiYy5aG]TO"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="|QY*!=!W^{Im55}Wzqu:"><field name="VALUE">copper</field></shadow></value><value name="B"><shadow type="var_block_text" id="$-b3#xyHnx98Ff5v~~N}"><field name="VALUE">lead</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="=Q/Mp9qMS8v}Z?_NIPEj"><field name="VALUE">copper</field></shadow><block type="logic_ternary" id="gTaV#d?Qn~N%KI!4Iq;L"><value name="IF"><block type="mind_op_var_binary" id="Qmpbhvjfi@{3U(4g{`N."><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="2tQ3Pz4t~.OG-brF,)k~"><field name="VALUE">copper</field></shadow></value><value name="B"><shadow type="var_block_text" id="=5C8y*+nQJfYa@Z+fE^m"><field name="VALUE">silicon</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text"><field name="VALUE">copper</field></shadow><block type="logic_ternary" id="OudzA]Du*lI.JuFVrD2f"><value name="IF"><block type="mind_op_var_binary" id="=Gm*wnPHsRKx+y140OQ!"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="9O$#biT,$9M{f=#iK,w4"><field name="VALUE">copper</field></shadow></value><value name="B"><shadow type="var_block_text" id="jQUr#eA7+AfIR?16Z.5n"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text"><field name="VALUE">copper</field></shadow><block type="mind_op_var_binary" id="Cic4~)i2m;;3b}Oj_Z6+"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="(MO2/=E+rehqw|^jGU_K"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id="O?24EX.4diw2%2ghKgjr"><field name="VALUE">copper</field></shadow></value></block></value><value name="ELSE"><shadow type="var_block_text"><field name="VALUE">lead</field></shadow><block type="mind_op_var_binary" id="4bw/Rc7L()HLTpLu3J=4"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="D.JZw%$_+c$c2QN4e6GB"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id="(|Cd:lfw:YRlG$DTYx~T"><field name="VALUE">titanium</field></shadow></value></block></value></block></value><value name="ELSE"><shadow type="var_block_text" id="X!ej[kdLyTa`!33gQ560"><field name="VALUE">lead</field></shadow><block type="logic_ternary" id="%Qzk7s6lG!weEdy?Sq+h"><value name="IF"><block type="mind_op_var_binary" id="*uEa?#`ZabQngqgQ$joF"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="|c$PB+SQ,OC1o!Kq~B13"><field name="VALUE">silicon</field></shadow></value><value name="B"><shadow type="var_block_text" id="Y@CB#MTi?t9)NfJ@d:JW"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text"><field name="VALUE">copper</field></shadow><block type="mind_op_var_binary" id="6%M#r~@{PCEfZ%58L#gA"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="V$/T*0{0wt6+|q?Eb1eS"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id="P},cQ@|Xp[AzrH5Cc#2h"><field name="VALUE">silicon</field></shadow></value></block></value><value name="ELSE"><shadow type="var_block_text"><field name="VALUE">lead</field></shadow><block type="mind_op_var_binary" id="RjXsljP0:67IpoPD6J*I"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="ts3EkivBa3cuX1-H3y;3"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id="CA?cH~qbH`,(;5EwBm7c"><field name="VALUE">titanium</field></shadow></value></block></value></block></value></block></value><value name="ELSE"><shadow type="var_block_text" id="]^kV1A!,$$u,aw.qzff~"><field name="VALUE">lead</field></shadow><block type="logic_ternary" id="@4UZ3xWz`4paS?^m/VD_"><value name="IF"><block type="mind_op_var_binary" id="E8gAIylOkm..MvWrAea|"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="2rz}-^N?znvud,q3LDAK"><field name="VALUE">lead</field></shadow></value><value name="B"><shadow type="var_block_text" id="JgR:X=IkSRY09uAN3%Qg"><field name="VALUE">silicon</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="!pmFubBLZ]$y,qP#ue,i"><field name="VALUE">copper</field></shadow><block type="logic_ternary" id="iq6;nw}V}#x(#h]f{]%_"><value name="IF"><block type="mind_op_var_binary" id="E#Cllg;)3[pW-epyvhbL"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="XDW[P1M#0NNQoS*63v|D"><field name="VALUE">lead</field></shadow></value><value name="B"><shadow type="var_block_text" id="K1jtaZ4)Pg,]?o@Y?]yU"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text"><field name="VALUE">copper</field></shadow><block type="mind_op_var_binary" id="Eab@5Jm}H~y7h[,0cK%p"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="fh`Svr?}G;XQV0rJbCpV"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id=")`~W]Ka/g:Z.vF00c-S="><field name="VALUE">lead</field></shadow></value></block></value><value name="ELSE"><shadow type="var_block_text"><field name="VALUE">lead</field></shadow><block type="mind_op_var_binary" id="@as*mM#iD:.G8#.5,WN7"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="aW81b[yitXD@AX2zy*o@"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id="_U=27lsvJQ{*Jn$}BCoF"><field name="VALUE">titanium</field></shadow></value></block></value></block></value><value name="ELSE"><shadow type="var_block_text" id="et,e1o+TY;@~`v3~[yic"><field name="VALUE">lead</field></shadow><block type="logic_ternary" id=":yR,Xy]lK2:9VedhP]og"><value name="IF"><block type="mind_op_var_binary" id="Pk^Jwe[52PPm*BDF/V#V"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="lBFlc^3vXnU3_oga{Y+$"><field name="VALUE">silicon</field></shadow></value><value name="B"><shadow type="var_block_text" id="g0U@M:YDIzu`cqu!Z97W"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="1O%JDM_d}H0|o4(;%o1y"><field name="VALUE">copper</field></shadow><block type="mind_op_var_binary" id="MPZ.TBga}EI?wFbWSMPk"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="goiXQe$IGvN_-P[EN;CL"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id="$ELzUMz7$9.47I^B9b^q"><field name="VALUE">silicon</field></shadow></value></block></value><value name="ELSE"><shadow type="var_block_text"><field name="VALUE">lead</field></shadow><block type="mind_op_var_binary" id="$BKcQ-bX~LJ%EI)xk+p6"><field name="OPERATOR">equal</field><value name="A"><shadow type="var_block_text" id="-oD9pk(dqR2BkOnG5beZ"><field name="VALUE">itemneeded</field></shadow></value><value name="B"><shadow type="var_block_text" id="rm=JaP39I!PYB8rl_^y:"><field name="VALUE">titanium</field></shadow></value></block></value></block></value></block></value></block></value></block></next></block></next></block></next></block></next></block></statement><value name="RETURN"><block type="var_block_text" id="[y3xz.No=`cM~11j[i2o"><field name="VALUE">itemneeded</field></block></value></block></xml>
```
Thank you.

**Comment by Meshiest** [comment]
Ah, the code generator for the ternary is broken at the moment, I will fix this real quick!

**Comment by Meshiest** [comment]
I've fixed the issue, the changes should be live shortly

**Comment by LargePrime** [comment]
thanks

**Comment by Meshiest** [comment]
`<xml xmlns="https://developers.google.com/blockly/xml"><variables><variable id="#RFo+f)fM5bg{3Tl6^u~">itemtype</variable><variable id="AcE15`,^(od4$!%;LT8/">howlong</variable></variables><block type="procedures_callnoreturn" id="[WGxZp}FY1{gx%FG/={I" x="870" y="-387"><mutation name="setunloaders"><arg name="itemtype"></arg></mutation><value name="ARG0"><block type="procedures_callreturn" id="eZ-|JN0AlbZK5.S$S-7_"><mutation name="smelterneeds"></mutation></block></value><next><block type="procedures_callnoreturn" id="|}Ppf1~ti+6+OI8CD,CQ"><mutation name="waitabit"><arg name="howlong"></arg></mutation><value name="ARG0"><block type="var_block_text" id="MUIZ0+(@K.(91{fM`l)T"><field name="VALUE">1000</field></block></value><next><block type="mind_end" id="`~wcOxZ_M{.VWl(w,3zM"></block></next></block></next></block><block type="procedures_defnoreturn" id="~_j!OTygYhs49#xXs_lY" x="866" y="-234"><mutation><arg name="howlong" varid="AcE15`,^(od4$!%;LT8/"></arg></mutation><field name="NAME">waitabit</field><comment pinned="false" h="80" w="160">Describe this function...</comment><statement name="STACK"><block type="mind_op_set_binary" id="z-6PNlmWkDMixhCPvSkD"><field name="DEST">result</field><field name="OPERATOR">add</field><value name="A"><shadow type="var_block_text" id="#-eEIFY3-}07r0Ipd+O:"><field name="VALUE">a</field></shadow><block type="global_self" id="]PuzuKV{dbv/wFhMELh("><field name="NAME">@time</field></block></value><value name="B"><shadow type="var_block_text" id="t?[WW~0V*%^scz?,bt},"><field name="VALUE">howlong</field></shadow></value><next><block type="loop_repeat_while" id="{65$-R!SCA.8XK_v6#4%"><value name="COND"><shadow type="var_block_text" id="GhBoBc2wN)CGp[MH5|Cw"><field name="VALUE">true</field></shadow><block type="mind_op_var_binary" id="6}eY/;vT5r.e~2iRPKBF"><field name="OPERATOR">greaterThan</field><value name="A"><shadow type="var_block_text" id="-D_-a?Jb*J!9]ZdOH~+-"><field name="VALUE">result</field></shadow></value><value name="B"><shadow type="var_block_text" id="[#ZaG(s5zvxQ59|1$n3f"><field name="VALUE">b</field></shadow><block type="global_self" id="dA_YIzHE*jFV,9f!%Zq%"><field name="NAME">@time</field></block></value></block></value></block></next></block></statement></block><block type="procedures_defnoreturn" id="uNAxK@r4,gP,Nv(Z{#l3" x="865" y="-69"><mutation><arg name="itemtype" varid="#RFo+f)fM5bg{3Tl6^u~"></arg></mutation><field name="NAME">setunloaders</field><comment pinned="false" h="80" w="160">Sets unloaders to item type</comment><statement name="STACK"><block type="mind_set" id="PTxwxAS1:u+=%wisdig@"><field name="DEST">unloader1</field><value name="VALUE"><shadow type="var_block_text" id="_3K@Q7vAdmgzim@n6)@p"><field name="VALUE">itemtype</field></shadow></value><next><block type="mind_set" id="^Qe7`B)gzX:yZE;uA,T("><field name="DEST">unloader2</field><value name="VALUE"><shadow type="var_block_text" id="yc0x}iA]ifK]=e1vDnS["><field name="VALUE">itemtype</field></shadow></value><next><block type="mind_set" id="f46}LiqUR$)]eiN[q1av"><field name="DEST">unloader3</field><value name="VALUE"><shadow type="var_block_text" id="+)U~!riE.G#Xd;qdt10I"><field name="VALUE">itemtype</field></shadow></value><next><block type="mind_set" id=".?sY[?w23*)17prBLL9{"><field name="DEST">unloader4</field><value name="VALUE"><shadow type="var_block_text" id="$zB4!Ld.LChZ$(UlFPP:"><field name="VALUE">itemtype</field></shadow></value></block></next></block></next></block></next></block></statement></block><block type="procedures_defreturn" id="~Ym*VfYPKQbELGe1Iot." x="856" y="102"><field name="NAME">smelterneeds</field><comment pinned="false" h="80" w="160">Describe this function...</comment><statement name="STACK"><block type="mind_sensor" id="g_5YWfP)XJy*,0Oq3$bI"><field name="DEST">copper</field><value name="FIELD"><shadow type="global_item" id="U(~}9ay00%eGFq_VDyu!"><field name="NAME">@copper</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="Id(9Um}Gg7;Mx,SbE(G9"><field name="VALUE">smelter1</field></shadow></value><next><block type="mind_sensor" id="4O*!_|V*^8=rz%yL*g/+"><field name="DEST">lead</field><value name="FIELD"><shadow type="global_item" id="W*^C2_(h76Ru,??2`*`L"><field name="NAME">@lead</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="1,5Llim08hnMk+`iCm$Y"><field name="VALUE">smelter1</field></shadow></value><next><block type="mind_sensor" id="-~H,FwE+6(O=.`YI_GmO"><field name="DEST">silicon</field><value name="FIELD"><shadow type="global_item" id="wQ:}c{hCHr}3%?w#onQ["><field name="NAME">@silicon</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="v4V^v))_Fdm2h;H9D93l"><field name="VALUE">smelter1</field></shadow></value><next><block type="mind_sensor" id="?FS+LH3JwO1!VSnvhV{G"><field name="DEST">titanium</field><value name="FIELD"><shadow type="global_item" id="=?{}62y|eF2M2g{AdGN`"><field name="NAME">@titanium</field></shadow></value><value name="UNIT"><shadow type="var_block_text" id="7OgBLa][:38_V(@*E)tj"><field name="VALUE">smelter1</field></shadow></value></block></next></block></next></block></next></block></statement><value name="RETURN"><block type="logic_ternary" id="rmVkBxkhU8pa?q1CMPm("><value name="IF"><block type="mind_op_var_binary" id="JDYCHeIj-HbiYy5aG]TO"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="|QY*!=!W^{Im55}Wzqu:"><field name="VALUE">copper</field></shadow></value><value name="B"><shadow type="var_block_text" id="$-b3#xyHnx98Ff5v~~N}"><field name="VALUE">lead</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="=Q/Mp9qMS8v}Z?_NIPEj"><field name="VALUE">copper</field></shadow><block type="logic_ternary" id="gTaV#d?Qn~N%KI!4Iq;L"><value name="IF"><block type="mind_op_var_binary" id="Qmpbhvjfi@{3U(4g{`N."><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="2tQ3Pz4t~.OG-brF,)k~"><field name="VALUE">copper</field></shadow></value><value name="B"><shadow type="var_block_text" id="=5C8y*+nQJfYa@Z+fE^m"><field name="VALUE">silicon</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text"><field name="VALUE">copper</field></shadow><block type="logic_ternary" id="OudzA]Du*lI.JuFVrD2f"><value name="IF"><block type="mind_op_var_binary" id="=Gm*wnPHsRKx+y140OQ!"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="9O$#biT,$9M{f=#iK,w4"><field name="VALUE">copper</field></shadow></value><value name="B"><shadow type="var_block_text" id="jQUr#eA7+AfIR?16Z.5n"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="IK%5$[2`rw(W`H-Gc9IV"><field name="VALUE">copper</field></shadow></value><value name="ELSE"><shadow type="var_block_text" id=":C,7MJr#}A~kET3i/k+H"><field name="VALUE">titanium</field></shadow></value></block></value><value name="ELSE"><shadow type="var_block_text" id="X!ej[kdLyTa`!33gQ560"><field name="VALUE">lead</field></shadow><block type="logic_ternary" id="%Qzk7s6lG!weEdy?Sq+h"><value name="IF"><block type="mind_op_var_binary" id="*uEa?#`ZabQngqgQ$joF"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="|c$PB+SQ,OC1o!Kq~B13"><field name="VALUE">silicon</field></shadow></value><value name="B"><shadow type="var_block_text" id="Y@CB#MTi?t9)NfJ@d:JW"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="*cnZAaD{[gNVjTEf=zp4"><field name="VALUE">silicon</field></shadow></value><value name="ELSE"><shadow type="var_block_text" id="W=VkICQ{d`F`ZwrP]%+Q"><field name="VALUE">titanium</field></shadow></value></block></value></block></value><value name="ELSE"><shadow type="var_block_text" id="]^kV1A!,$$u,aw.qzff~"><field name="VALUE">lead</field></shadow><block type="logic_ternary" id="@4UZ3xWz`4paS?^m/VD_"><value name="IF"><block type="mind_op_var_binary" id="E8gAIylOkm..MvWrAea|"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="2rz}-^N?znvud,q3LDAK"><field name="VALUE">lead</field></shadow></value><value name="B"><shadow type="var_block_text" id="JgR:X=IkSRY09uAN3%Qg"><field name="VALUE">silicon</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="!pmFubBLZ]$y,qP#ue,i"><field name="VALUE">copper</field></shadow><block type="logic_ternary" id="iq6;nw}V}#x(#h]f{]%_"><value name="IF"><block type="mind_op_var_binary" id="E#Cllg;)3[pW-epyvhbL"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="XDW[P1M#0NNQoS*63v|D"><field name="VALUE">lead</field></shadow></value><value name="B"><shadow type="var_block_text" id="K1jtaZ4)Pg,]?o@Y?]yU"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="HS(nHCv(-O1b8A3%en39"><field name="VALUE">lead</field></shadow></value><value name="ELSE"><shadow type="var_block_text" id="*%ELjW(K4W!gZDT(9]0_"><field name="VALUE">titanium</field></shadow></value></block></value><value name="ELSE"><shadow type="var_block_text" id="et,e1o+TY;@~`v3~[yic"><field name="VALUE">lead</field></shadow><block type="logic_ternary" id=":yR,Xy]lK2:9VedhP]og"><value name="IF"><block type="mind_op_var_binary" id="Pk^Jwe[52PPm*BDF/V#V"><field name="OPERATOR">lessThan</field><value name="A"><shadow type="var_block_text" id="lBFlc^3vXnU3_oga{Y+$"><field name="VALUE">silicon</field></shadow></value><value name="B"><shadow type="var_block_text" id="g0U@M:YDIzu`cqu!Z97W"><field name="VALUE">titanium</field></shadow></value></block></value><value name="THEN"><shadow type="var_block_text" id="1O%JDM_d}H0|o4(;%o1y"><field name="VALUE">silicon</field></shadow></value><value name="ELSE"><shadow type="var_block_text" id="si#fAOw9F5*?H}Obd2Se"><field name="VALUE">titanium</field></shadow></value></block></value></block></value></block></value></block><block type="var_block_text" id="[y3xz.No=`cM~11j[i2o" x="1118" y="358"><field name="VALUE">itemneeded</field></block></xml>`

this might do what you wanted
